#!/bin/bash
set -eu

detach=""
if [ "${1:-}" == "detach" ]; then
  detach="--detach"
fi

docker stop slippy-tile-proxy 2> /dev/null > /dev/null || true
docker build -t slippy-tile-proxy .
docker run ${detach} --name slippy-tile-proxy --rm --publish 8080:8080/tcp slippy-tile-proxy
