#!/bin/bash
set -eu

detach=""
if [ "${1:-}" == "detach" ]; then
  detach="--detach"
fi

HOST_BIND_PORT=8080
CONTAINER_BIND_PORT=8080
WAND_MEMORY_LIMIT=2GiB

docker stop slippy-tile-proxy 2> /dev/null > /dev/null || true
docker build \
  --build-arg WAND_MEMORY_LIMIT=${WAND_MEMORY_LIMIT} \
  --tag slippy-tile-proxy .
docker run --name slippy-tile-proxy \
  ${detach} \
  --rm \
  --publish "${HOST_BIND_PORT}:${CONTAINER_BIND_PORT}/tcp" \
  --env BIND_PORT="${CONTAINER_BIND_PORT}" \
  slippy-tile-proxy
