#!/bin/bash
set -eu

detach=""
if [ "${1:-}" == "detach" ]; then
	detach="--detach"
fi

HOST_BIND_PORT=8080
CONTAINER_BIND_PORT=8080
# Use a large WAND_MEMORY_LIMIT if you plan to use the
# geonorge provider. 8GB is the minimum recommended value
# to prevent running out of memory when QGIS (or other
# aggressive programs) send an excessive number of requests
WAND_MEMORY_LIMIT=${WAND_MEMORY_LIMIT:-8GiB}

docker stop slippy-tile-proxy 2>/dev/null >/dev/null || true
docker build --target prog_runtime \
	--build-arg WAND_MEMORY_LIMIT="${WAND_MEMORY_LIMIT}" \
	--tag slippy-tile-proxy .
docker run --name slippy-tile-proxy \
	${detach} \
	--rm \
	--publish "${HOST_BIND_PORT}:${CONTAINER_BIND_PORT}/tcp" \
	--env BIND_PORT="${CONTAINER_BIND_PORT}" \
	slippy-tile-proxy
